.TH LOOLWSD-GENERATE_PROOF_KEY "1" "April 2020" "coolwsd-generate-proof-key " "User Commands"
.SH NAME
coolwsd-generate-proof-key \- Utility that genarates WOPI Proof keys for Collabora Online
.SH SYNOPSIS
coolwsd-generate-proof-key
.SH DESCRIPTION
coolwsd-generate-proof-key creates an RSA key pair in /etc/loolwsd for the WOPI Proof headers. The script is automatically run by the postinstall script of loolwsd package, but in case of failure sysadmins can run it manually.
.SH "SEE ALSO"
coolforkit(1), coolconvert(1), coolconfig(1), loolwsd(1), coolwsd-systemplate-setup(1), coolmount(1)
