.TH COOLFORKIT "1" "May 2018" "coolforkit " "User Commands"
.SH NAME
coolforkit \- Utility that spawns LOK instances for Collabora Online
.SH SYNOPSIS
coolforkit OPTIONS
.SH DESCRIPTION
Single-threaded process that spawns LibreOfficeKit (LOK) instances.
.PP
\fBNote\fR: Running this standalone is not possible. It is spawned by loolwsd and is controlled via a pipe.
.SH "SEE ALSO"
loolwsd(1), coolconvert(1), coolconfig(1), loolforkit-systemplate-setup(1), coolwsd-generate-proof-key(1), coolmount(1)
