.TH COOLMOUNT "1" "May 2018" "coolmount " "User Commands"
.SH NAME
coolmount \- A very tiny helper to allow overlay mounting for Collabora Online
.SH SYNOPSIS
coolmount OPTIONS
.SH DESCRIPTION
This is a very tiny helper to allow overlay mounting.
.PP
\fBNote\fR: Running this standalone is not possible. It is used internally by loolwsd when it creates the jail for the document.
.SH "SEE ALSO"
loolwsd(1), loolconvert(1), coolconfig(1), loolforkit-systemplate-setup(1), loolwsd-generate-proof-key(1), coolforkit(1)
