.TH LOOLCONVERT "1" "May 2018" "loolconvert" "User Commands"
.SH NAME
loolconvert \- Collabora Online document converter tool
.SH SYNOPSIS
loolconvert OPTIONS FILE(S)
.SH OPTIONS
\fB\-\-help\fR                  Display help information on command line arguments.
.PP
\fB\-\-extension\fR=\fIformat\fR      file format extension to convert to
.PP
\fB\-\-outdir\fR=\fIoutdir\fR         output directory for converted files
.PP
\fB\-\-parallelism\fR=\fIthreads\fR   number of simultaneous threads to use
.PP
\fB\-\-server\fR=\fIuri\fR            URI of COOL server
.PP
\fB\-\-no\-check\-certificate\fR  Disable checking of SSL certs
.PP
.SH "SEE ALSO"
loolwsd(1), coolforkit(1), coolconfig(1), loolforkit-systemplate-setup(1), loolwsd-generate-proof-key(1), coolmount(1)
