.TH LOOLWSD-SYSTEMPLATE-SETUP "1" "May 2018" "loolwsd-systemplate-setup " "User Commands"
.SH NAME
loolwsd-systemplate-setup \- Utility that sets up system template for Collabora Online
.SH SYNOPSIS
loolwsd-systemplate-setup <chroot template directory for system libs to create> <LibreOffice installation directory>
.SH DESCRIPTION
loolwsd-systemplate-setup creates a minimal system template for running the LibreOfficeKit in a chroot jail. The system template contains the bare minimum of system libraries to run LibreOfficeKit, and also fonts and locale data from the system.
.SH "SEE ALSO"
coolforkit(1), loolconvert(1), coolconfig(1), loolwsd(1), loolwsd-generate-proof-key(1), coolmount(1)
