.TH LOOLWSD-GENERATE_PROOF_KEY "1" "April 2020" "loolwsd-generate-proof-key " "User Commands"
.SH NAME
loolwsd-generate-proof-key \- Utility that genarates WOPI Proof keys for Collabora Online
.SH SYNOPSIS
loolwsd-generate-proof-key
.SH DESCRIPTION
loolwsd-generate-proof-key creates an RSA key pair in /etc/loolwsd for the WOPI Proof headers. The script is automatically run by the postinstall script of loolwsd package, but in case of failure sysadmins can run it manually.
.SH "SEE ALSO"
loolforkit(1), loolconvert(1), coolconfig(1), loolwsd(1), loolwsd-systemplate-setup(1), loolmount(1)
