.TH LOOLFORKIT "1" "May 2018" "loolforkit " "User Commands"
.SH NAME
loolforkit
.SH SYNOPSYS
loolforkit OPTIONS
.SH DESCRIPTION
Single-threaded process that spawns LibreOffice Online Kit (LOK) instances.
.PP
\fBNote\fR: Running this standalone is not possible. It is spawned by loolwsd and is controlled via a pipe.
.SH "SEE ALSO"
loolwsd(1), loolconvert(1), loolconfig(1), loolforkit-systemplate-setup(1)
