# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  Thanks for opening this pull request!

  Things that will help get your PR across the finish line:

  - Check out our [contributing guidelines](https://github.com/CollaboraOnline/online/blob/master/CONTRIBUTING.md).
  - Connect with us through one of [our communication channels](https://collaboraonline.github.io/post/communicate/).
  - Click on the details link next to the failing CI checks, if any, to see an explanation on how to fix it.
  - Feel free to ping @Darshan-upadhyay1110 or the mentor of the easyHack you are solving if you need help. CC: @pedropintosilva
  - Explore more Easy Hacks to dive deeper into Collabora Online and start contributing:https://github.com/CollaboraOnline/online/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22Easy%20Hack%22
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
  Thanks a lot for your contribution, and congrats on your first pull request merged! Welcome aboard! 🎉🎉🎉

  If you haven't decided on your next task yet, take a look at our [easy-hacks](https://github.com/CollaboraOnline/online/issues?q=is%3Aissue+is%3Aopen+easy+label%3A%22Easy+Hack%22). We're looking forward to your next pull request! :)

