image:
  file: .gitpod.dockerfile

ports:
  - port: 9980
    onOpen: ignore
  - port: 6080
    protocol: "http"
  - port: 5900
    onOpen: ignore

vscode:
  extensions:
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false

# Update URL unders tasks after any major release,
# on a daily-basis there is a core tar ball that it's used by gitpod during prebuilds:
# 1. Ping infra team to re-configure with the new URL
# 2. Update URL here under tasks
tasks:
  - init: cd .. && wget https://github.com/CollaboraOnline/online/releases/download/for-code-assets/core-co-2021-assets.tar.gz
    prebuild: tar xvf core-co-2021-assets.tar.gz && rm core-co-2021-assets.tar.gz && cd online && ./autogen.sh && ./configure --enable-silent-rules --with-lokit-path=/workspace/include --with-lo-path=/workspace/instdir --enable-debug --disable-setcap && cp .gitpod-files/loolwsd-gitpod.xml loolwsd.xml && mkdir .vscode && cp .gitpod-files/settings.json .vscode/settings.json && make -j `nproc`

