image:
  file: .gitpod.dockerfile

ports:
  - port: 9980
    onOpen: ignore
  - port: 6080
    onOpen: "open-browser"
  - port: 5900
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false

# Update URL unders tasks after any major release,
# on a daily-basis there is a core tar ball that it's used by gitpod during prebuilds:
# 1. Ping infra team to re-configure with the new URL
# 2. Update URL here under tasks
tasks:
  - name: Get Core & Configure
    before: |
      cd ..
      wget https://github.com/CollaboraOnline/online/releases/download/for-code-assets/core-co-23.05-assets.tar.gz
      tar xvf core-co-23.05-assets.tar.gz
      rm core-co-23.05-assets.tar.gz
      cd online
    init: |
      ./autogen.sh
      ./configure --enable-silent-rules --with-lokit-path=/workspace/include --with-lo-path=/workspace/instdir --enable-debug -enable-cypress --disable-setcap
      gp sync-done configuring
      cp .gitpod-files/coolwsd-gitpod.xml coolwsd.xml
      mkdir .vscode
      cp .gitpod-files/settings.json .vscode/settings.json
  - name: Building
    init: gp sync-await configuring
    command: make -j$(nproc) run
  - name: Test
    init: gp await-port 9980
    command: |
      echo "If you are not using the VS Code desktop and instead just your web browser, to open and test Collabora Online:"
      echo "1. Make sure your web browser is not blocking any tabs from opening;"
      echo "2. Check that you have the VCN tab opened (if not, open it up from the left side Remote explorer > 6080)"
      echo "3. In the terminal where make is running: scroll and copy the the URL ending with: hello-world.odt"
      echo "4. In a new terminal execute the following:"
      echo "   firefox  [paste copied URL here]"
    openMode: split-right

