{{- if and .Values.prometheus.servicemonitor.enabled .Values.languagetool.enabled .Values.languagetool.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "collabora-online.fullname" . }}-languagetool
  labels:
    {{- include "collabora-online.labels" . | nindent 4 }}
    {{- with .Values.prometheus.servicemonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      {{- include "collabora-online.selectorLabels" . | nindent 6 }}
      type: languagetool
{{- end }}
