module.exports.list = {
	fontColor: ['#Home #FontColor .arrowbackground', '#tb_editbar_item_fontcolor'],
	fontName: ['#fontnamecombobox', '#tb_editbar_item_fonts'],
	bold: ['#Bold', '#tb_editbar_item_bold'],
	italic: ['#Italic', '#tb_editbar_item_italic'],
	underline: ['#Underline', '#tb_editbar_item_underline'],
	strikeout: ['#Strikeout', '#tb_editbar_item_strikeout'],
	fontSize: ['#fontsize', '#tb_editbar_item_fontsizes'],
	leftPara: ['#LeftPara', '#tb_editbar_item_leftpara'],
	rightPara: ['#RightPara', '#tb_editbar_item_rightpara'],
	centerPara: ['#CenterPara', '#tb_editbar_item_centerpara'],
	justifyPara: ['#JustifyPara', '#tb_editbar_item_justifypara'],
	lineSpacing: ['#LineSpacing', '#tb_editbar_item_linespacing'],
	numberedList: ['#DefaultNumbering', '#tb_editbar_item_defaultnumbering'],
	bulletList: ['#DefaultBullet', '#tb_editbar_item_defaultbullet'],
	incrementIndent: ['#IncrementIndent', '#tb_editbar_item_incrementindent'],
	decrementIndent: ['#DecrementIndent', '#tb_editbar_item_decrementindent'],
	insertAnnotation: ['#InsertAnnotationimg', '#tb_editbar_item_insertannotation'],
	insertTable: ['#InsertTable', '#tb_editbar_item_inserttable'],
	insertGraphic: ['#InsertGraphic', '#tb_editbar_item_insertgraphic'],
	clearFormat: ['#Home .unoResetAttributes', '#tb_editbar_item_reset'],
	hyperLink: ['#HyperlinkDialog', '#tb_editbar_item_link'],
	insertShape: ['#BasicShapes', '#tb_editbar_item_insertshapes'],
	save: ['#Save', '#tb_editbar_item_save'],
	print: ['#Print', '#tb_editbar_item_print'],
	undo: ['#Undo', '#tb_editbar_item_undo'],
	redo: ['#Redo', '#tb_editbar_item_redo'],
	insertChart: ['#InsertObjectChart', '#tb_editbar_item_insertobjectchart'],
	insertSymbol: ['#CharmapControl', '#tb_editbar_item_insertsymbol'],
	formatBrush: ['#FormatPaintbrush', '#tb_editbar_item_formatpaintbrush'],
	sidebar: ['.unospan-optionstoolboxdown.unoSidebar', '#tb_editbar_item_sidebar'],
	backColor: ['#Home #BackColor .arrowbackground', '#tb_editbar_item_backcolor'],
	borderStyle: ['#SetBorderStyle', '#tb_editbar_item_setborderstyle'],
	backgroundColor: ['#Home #BackgroundColor .arrowbackground','#tb_editbar_item_backgroundcolor'],
	fileTab: ['#File-tab-label', '#menu-file'],
	documentProperties: ['#SetDocumentProperties', '#menu-properties'],
};
