/* -*- js-indent-level: 8 -*- */
module.exports.list = {
	fontColor: ['#Home #home-color .unoarrow', '#toolbar-up [id^="fontcolor"]'],
	fontName: ['#fontnamecombobox.notebookbar > .ui-combobox-button', '#toolbar-up #fontnamecombobox'],
	bold: ['#Bold', '#toolbar-up #bold'],
	italic: ['#Italic', '#toolbar-up #italic'],
	underline: ['#Underline', '#toolbar-up #underline'],
	strikeout: ['#Strikeout', '#toolbar-up #strikeout'],
	fontSize: ['#fontsizecombobox.notebookbar > .ui-combobox-button', '#toolbar-up #fontsizecombobox'],
	leftPara: ['#LeftPara', '#toolbar-up #leftpara'],
	rightPara: ['#RightPara', '#toolbar-up #rightpara'],
	centerPara: ['#CenterPara', '#toolbar-up #centerpara'],
	justifyPara: ['#JustifyPara', '#toolbar-up #justifypara'],
	lineSpacing: ['#LineSpacing', '#toolbar-up #linespacing'],
	numberedList: ['#DefaultNumbering', '#toolbar-up #defaultnumbering'],
	bulletList: ['#DefaultBullet', '#toolbar-up #defaultbullet'],
	incrementIndent: ['#IncrementIndent', '#toolbar-up #incrementindent'],
	decrementIndent: ['#DecrementIndent', '#toolbar-up #decrementindent'],
	insertAnnotation: ['#InsertAnnotation', '#toolbar-up #insertannotation'],
	insertTable: ['#InsertTable', '#toolbar-up #inserttable'],
	insertGraphic: ['#InsertGraphic', '#toolbar-up #insertgraphic'],
	clearFormat: ['#Home .unoResetAttributes', '#toolbar-up #reset'],
	hyperLink: ['#HyperlinkDialog', '#toolbar-up #link'],
	insertShape: ['#BasicShapes', '#toolbar-up #insertshapes'],
	save: ['#Save', '#toolbar-up #save'],
	print: ['#Print', '#toolbar-up #print'],
	undo: ['#Undo', '#toolbar-up #undo'],
	redo: ['#Redo', '#toolbar-up #redo'],
	insertChart: ['#InsertObjectChart', '#toolbar-up #insertobjectchart'],
	insertSymbol: ['#CharmapControl', '#toolbar-up #insertsymbol'],
	formatBrush: ['#FormatPaintbrush', '#toolbar-up #formatpaintbrush'],
	sidebar: ['.unospan-optionstoolboxdown.unoSidebar', '#toolbar-up #sidebar'],
	backColor: ['#Home #home-back-color .unoarrow', '#toolbar-up #backcolor'],
	borderStyle: ['#SetBorderStyle', '#toolbar-up #setborderstyle'],
	backgroundColor: ['#Home #home-background-color .unoarrow','#toolbar-up #backgroundcolor'],
	fileTab: ['#File-tab-label', '#menu-file'],
	documentProperties: ['#SetDocumentProperties', '#menu-properties'],
};
