// Don't modify, generated using unocommands.py

var unoCommandsArray = {
	'AcceptAllTrackedChanges':{text:{context:_('Accept All Changes'),menu:_('Accept All'),},},
	'AcceptTrackedChange':{text:{context:_('Accept Change'),menu:_('Accept'),},},
	'AcceptTrackedChangeToNext':{text:{context:_('Accept Track Change and select the next one'),menu:_('Accept and Move to Next'),},},
	'AcceptTrackedChanges':{text:{context:_('Manage Track Changes'),menu:_('~Manage...'),},},
	'AddName':{spreadsheet:{menu:_('~Define...'),},},
	'AlignBlock':{spreadsheet:{menu:_('Justified'),},},
	'AlignBottom':{spreadsheet:{menu:_('Align Bottom'),},text:{menu:_('Align Bottom to Anchor'),},},
	'AlignCenter':{global:{menu:_('~Centered'),},},
	'AlignDown':{global:{menu:_('~Bottom'),},},
	'AlignHorizontalCenter':{spreadsheet:{menu:_('Align Center'),},text:{menu:_('Center Horizontal'),},},
	'AlignLeft':{spreadsheet:{menu:_('Align Left'),},text:{menu:_('Align Left'),},},
	'AlignMiddle':{global:{menu:_('C~enter'),},},
	'AlignRight':{spreadsheet:{menu:_('Align Right'),},text:{menu:_('Align Right'),},},
	'AlignTop':{spreadsheet:{menu:_('Align Top'),},text:{menu:_('Align Top to Anchor'),},},
	'AlignUp':{global:{menu:_('~Top'),},},
	'AlignVCenter':{spreadsheet:{menu:_('Center Vertically'),},},
	'AnalysisOfVarianceDialog':{spreadsheet:{menu:_('~Analysis of Variance (ANOVA)...'),},},
	'AnchorMenu':{global:{menu:_('Anc~hor'),},},
	'ArrangeFrameMenu':{text:{menu:_('Arrange'),},},
	'ArrangeMenu':{global:{menu:_('A~rrange'),},presentation:{menu:_('~Arrange'),},},
	'AutoFormatMenu':{text:{menu:_('AutoCorr~ect'),},},
	'BackColor':{text:{menu:_('Highlight Color'),},},
	'BackgroundColor':{global:{menu:_('Background Color'),},},
	'Backward':{global:{menu:_('Send Back~ward'),},presentation:{menu:_('Send Back~ward'),},},
	'BasicShapes':{global:{context:_('Shapes'),menu:_('Shapes'),},},
	'BibliographyComponent':{global:{menu:_('~Bibliography Database'),},},
	'Bold':{global:{menu:_('Bold'),},},
	'BringToFront':{global:{menu:_('~Bring to Front'),},},
	'Calculate':{spreadsheet:{menu:_('~Recalculate'),},},
	'CellVertBottom':{global:{context:_('Align Bottom'),menu:_('Bottom'),},},
	'CellVertCenter':{global:{context:_('Center Vertically'),menu:_('Center'),},},
	'CellVertTop':{global:{context:_('Align Top'),menu:_('Top'),},},
	'CenterPara':{global:{context:_('Align Center'),menu:_('Center'),},},
	'ChangeCaseRotateCase':{global:{menu:_('Cycle Case'),},},
	'ChangeCaseToLower':{global:{menu:_('~lowercase'),},},
	'ChangeCaseToSentenceCase':{global:{menu:_('~Sentence case'),},},
	'ChangeCaseToTitleCase':{global:{menu:_('~Capitalize Every Word'),},},
	'ChangeCaseToToggleCase':{global:{menu:_('~tOGGLE cASE'),},},
	'ChangeCaseToUpper':{global:{menu:_('~UPPERCASE'),},},
	'ChangesMenu':{global:{menu:_('Track Chan~ges'),},},
	'ChapterNumberingDialog':{text:{menu:_('Chapter ~Numbering...'),},},
	'CharBackColor':{global:{menu:_('Highlight Color'),},},
	'CharmapControl':{global:{context:_('Insert Special Characters'),menu:_('Symbol'),},},
	'ChiSquareTestDialog':{spreadsheet:{menu:_('~Chi-square Test...'),},},
	'ClearOutline':{global:{menu:_('~Remove Outline'),},},
	'Color':{global:{menu:_('Font Color'),},},
	'ColorScaleFormatDialog':{spreadsheet:{menu:_('Color Scale...'),},},
	'ColumnOperations':{spreadsheet:{menu:_('Column'),},},
	'Combine':{presentation:{menu:_('Comb~ine'),},},
	'CommonAlignBottom':{global:{menu:_('Bottom'),},},
	'CommonAlignHorizontalCenter':{global:{menu:_('Centered'),},},
	'CommonAlignJustified':{global:{menu:_('Justified'),},},
	'CommonAlignLeft':{global:{menu:_('Left'),},},
	'CommonAlignRight':{global:{menu:_('Right'),},},
	'CommonAlignTop':{global:{menu:_('Top'),},},
	'CommonAlignVerticalCenter':{global:{menu:_('Center'),},},
	'CondDateFormatDialog':{spreadsheet:{menu:_('Date...'),},},
	'ConditionalFormatDialog':{spreadsheet:{menu:_('Condition...'),},},
	'ConditionalFormatManagerDialog':{spreadsheet:{menu:_('Manage...'),},},
	'ConditionalFormatMenu':{spreadsheet:{menu:_('C~onditional'),},},
	'ConnectorToolbox':{presentation:{menu:_('Connectors'),},},
	'ContinueNumbering':{text:{menu:_('Continue previous numbering'),},},
	'ContourDialog':{global:{menu:_('~Edit Contour...'),},},
	'ControlCodes':{text:{context:_('Toggle Formatting Marks'),menu:_('For~matting Marks'),},},
	'Copy':{global:{menu:_('Cop~y'),},},
	'CopyHyperlinkLocation':{global:{menu:_('Copy Hyperlink Location'),},},
	'CorrelationDialog':{spreadsheet:{menu:_('~Correlation...'),},},
	'CovarianceDialog':{spreadsheet:{menu:_('~Covariance...'),},},
	'CustomAnimation':{presentation:{menu:_('Animation'),},},
	'Cut':{global:{menu:_('~Cut'),},},
	'DataBarFormatDialog':{spreadsheet:{menu:_('Data Bar...'),},},
	'DataDataPilotRun':{spreadsheet:{context:_('~Properties...'),menu:_('Pi~vot Table...'),},},
	'DataFilterAutoFilter':{spreadsheet:{menu:_('Auto~Filter'),},},
	'DataFilterHideAutoFilter':{spreadsheet:{menu:_('~Hide AutoFilter'),},},
	'DataFilterRemoveFilter':{spreadsheet:{menu:_('~Reset Filter'),},},
	'DataFilterSpecialFilter':{spreadsheet:{menu:_('~Advanced Filter...'),},},
	'DataFilterStandardFilter':{spreadsheet:{menu:_('~Standard Filter...'),},},
	'DataMenu':{global:{menu:_('~Data'),},},
	'DataPilotMenu':{spreadsheet:{menu:_('~Pivot Table'),},},
	'DataRanges':{global:{menu:_('~Data Ranges...'),},},
	'DataSort':{spreadsheet:{menu:_('~Sort...'),},},
	'DecrementIndent':{global:{context:_('Decrease Indent'),menu:_('Decrease Indent'),},},
	'DecrementLevel':{text:{menu:_('Demote One Level'),},},
	'DecrementSubLevels':{text:{menu:_('Demote One Level With Subpoints'),},},
	'DefaultBullet':{global:{context:_('Toggle Bulleted List'),menu:_('~Bulleted List'),},},
	'DefaultNumbering':{global:{context:_('Toggle Numbered List'),menu:_('~Numbered List'),},},
	'DefineName':{spreadsheet:{menu:_('~Manage...'),},},
	'DelBreakMenu':{spreadsheet:{menu:_('Delete Page ~Break'),},},
	'Delete':{global:{menu:_('Delete C~ontents...'),},spreadsheet:{context:_('Cl~ear Contents...'),menu:_('Cle~ar Cells...'),},},
	'DeleteAllAnnotation':{presentation:{menu:_('Delete ~All Comments'),},},
	'DeleteAllNotes':{global:{menu:_('Delete All Comments'),},spreadsheet:{menu:_('Delete All Comments'),},},
	'DeleteAuthor':{global:{menu:_('Delete All Comments by This Author'),},},
	'DeleteAxis':{global:{menu:_('Delete Axis'),},},
	'DeleteCell':{spreadsheet:{menu:_('Delete C~ells...'),},},
	'DeleteColumnbreak':{spreadsheet:{menu:_('~Column Break'),},},
	'DeleteColumns':{presentation:{menu:_('Delete Column'),},spreadsheet:{menu:_('Delete Columns'),},text:{context:_('Delete selected columns'),menu:_('~Columns'),},},
	'DeleteComment':{global:{menu:_('Delete Comment'),},},
	'DeleteDataLabel':{global:{menu:_('Delete Single Data Label'),},},
	'DeleteLegend':{global:{menu:_('Delete Legend'),},},
	'DeleteMajorGrid':{global:{menu:_('Delete Major Grid'),},},
	'DeleteMinorGrid':{global:{menu:_('Delete Minor Grid'),},},
	'DeleteNote':{spreadsheet:{menu:_('Delete Comment'),},},
	'DeletePage':{presentation:{menu:_('D~elete Page'),},},
	'DeletePivotTable':{spreadsheet:{menu:_('~Delete'),},},
	'DeleteRowbreak':{spreadsheet:{menu:_('~Row Break'),},},
	'DeleteRows':{presentation:{menu:_('Delete Row'),},spreadsheet:{menu:_('Delete Rows'),},text:{context:_('Delete selected rows'),menu:_('~Rows'),},},
	'DeleteSlide':{presentation:{menu:_('~Delete Slide'),},},
	'DeleteTable':{presentation:{menu:_('Delete Table'),},text:{context:_('Delete table'),menu:_('~Table'),},},
	'DescriptiveStatisticsDialog':{spreadsheet:{menu:_('~Descriptive Statistics...'),},},
	'DiagramData':{global:{menu:_('~Data Table...'),},},
	'DiagramType':{global:{menu:_('Chart T~ype...'),},},
	'Dismantle':{presentation:{menu:_('Spl~it'),},},
	'DistributeSelection':{global:{context:_('Select at least three objects to distribute'),menu:_('~Distribution'),},},
	'DownSearch':{global:{menu:_('Find Next'),},},
	'DrawText':{global:{context:_('Insert Text Box'),menu:_('~Text Box'),},},
	'DuplicatePage':{presentation:{menu:_('Duplicate Page'),},},
	'DuplicateSlide':{presentation:{menu:_('Duplicate ~Slide'),},},
	'EditHeaderAndFooter':{spreadsheet:{menu:_('~Headers and Footers...'),},},
	'EditHyperlink':{global:{context:_('Edit Hyperlink...'),menu:_('~Hyperlink'),},},
	'EditMenu':{global:{menu:_('~Edit'),},},
	'EditRegion':{text:{menu:_('~Sections...'),},},
	'EditStyle':{global:{menu:_('~Edit Style...'),},presentation:{menu:_('E~dit Style...'),},},
	'EnterGroup':{global:{menu:_('~Enter Group'),},},
	'EntireCell':{text:{context:_('Select Cell'),menu:_('C~ell'),},},
	'EntireColumn':{presentation:{menu:_('Select Column'),},text:{menu:_('~Column'),},},
	'EntireRow':{presentation:{menu:_('Select Row'),},text:{menu:_('~Row'),},},
	'ExponentialSmoothingDialog':{spreadsheet:{menu:_('~Exponential Smoothing...'),},},
	'FTestDialog':{spreadsheet:{menu:_('~F-test...'),},},
	'FillColor':{global:{menu:_('Fill Color'),},},
	'FilterMenu':{spreadsheet:{menu:_('More ~Filters'),},},
	'FlipHorizontal':{global:{menu:_('Flip Horizontally'),},},
	'FlipVertical':{global:{menu:_('Flip Vertically'),},},
	'FontColor':{global:{menu:_('Font Color'),},text:{menu:_('Font Color'),},},
	'FontDialog':{global:{menu:_('C~haracter...'),},},
	'FontworkGalleryFloater':{global:{context:_('Insert Fontwork Text'),menu:_('Fontwork...'),},},
	'FontworkShapeType':{global:{menu:_('Fontwork Shape'),},},
	'FontworkShapeType.fontwork-arch-down-curve':{global:{menu:_('Arch Down (Curve)'),},},
	'FontworkShapeType.fontwork-arch-down-pour':{global:{menu:_('Arch Down (Pour)'),},},
	'FontworkShapeType.fontwork-arch-left-curve':{global:{menu:_('Arch Left (Curve)'),},},
	'FontworkShapeType.fontwork-arch-right-curve':{global:{menu:_('Arch Right (Curve)'),},},
	'FontworkShapeType.fontwork-arch-right-pour':{global:{menu:_('Arch Right (Pour)'),},},
	'FontworkShapeType.fontwork-arch-up-curve':{global:{menu:_('Arch Up (Curve)'),},},
	'FontworkShapeType.fontwork-arch-up-pour':{global:{menu:_('Arch Up (Pour)'),},},
	'FontworkShapeType.fontwork-chevron-down':{global:{menu:_('Chevron Down'),},},
	'FontworkShapeType.fontwork-chevron-up':{global:{menu:_('Chevron Up'),},},
	'FontworkShapeType.fontwork-circle-curve':{global:{menu:_('Circle (Curve)'),},},
	'FontworkShapeType.fontwork-circle-pour':{global:{menu:_('Circle (Pour)'),},},
	'FontworkShapeType.fontwork-curve-down':{global:{menu:_('Curve Down'),},},
	'FontworkShapeType.fontwork-curve-up':{global:{menu:_('Curve Up'),},},
	'FontworkShapeType.fontwork-fade-down':{global:{menu:_('Fade Down'),},},
	'FontworkShapeType.fontwork-fade-left':{global:{menu:_('Fade Left'),},},
	'FontworkShapeType.fontwork-fade-right':{global:{menu:_('Fade Right'),},},
	'FontworkShapeType.fontwork-fade-up':{global:{menu:_('Fade Up'),},},
	'FontworkShapeType.fontwork-fade-up-and-left':{global:{menu:_('Fade Up and Left'),},},
	'FontworkShapeType.fontwork-fade-up-and-right':{global:{menu:_('Fade Up and Right'),},},
	'FontworkShapeType.fontwork-inflate':{global:{menu:_('Inflate'),},},
	'FontworkShapeType.fontwork-open-circle-curve':{global:{menu:_('Open Circle (Curve)'),},},
	'FontworkShapeType.fontwork-open-circle-pour':{global:{menu:_('Open Circle (Pour)'),},},
	'FontworkShapeType.fontwork-plain-text':{global:{menu:_('Plain Text'),},},
	'FontworkShapeType.fontwork-slant-down':{global:{menu:_('Slant Down'),},},
	'FontworkShapeType.fontwork-slant-up':{global:{menu:_('Slant Up'),},},
	'FontworkShapeType.fontwork-stop':{global:{menu:_('Stop'),},},
	'FontworkShapeType.fontwork-triangle-down':{global:{menu:_('Triangle Down'),},},
	'FontworkShapeType.fontwork-triangle-up':{global:{menu:_('Triangle Up'),},},
	'FontworkShapeType.fontwork-wave':{global:{menu:_('Wave'),},},
	'FootnoteDialog':{text:{menu:_('~Footnotes and Endnotes...'),},},
	'FormatArea':{global:{menu:_('A~rea...'),},},
	'FormatAxis':{global:{menu:_('Format Axis...'),},},
	'FormatBulletsMenu':{global:{menu:_('Lis~ts'),},},
	'FormatCellDialog':{spreadsheet:{context:_('~Format Cells...'),menu:_('Ce~lls...'),},},
	'FormatChartArea':{global:{menu:_('Format Chart Area...'),},},
	'FormatColumns':{text:{menu:_('Co~lumns...'),},},
	'FormatDataLabel':{global:{menu:_('Format Single Data Label...'),},},
	'FormatDataLabels':{global:{menu:_('Format Data Labels...'),},},
	'FormatDataPoint':{global:{menu:_('Format Data Point...'),},},
	'FormatDataSeries':{global:{menu:_('Format Data Series...'),},},
	'FormatFloor':{global:{menu:_('Format Floor...'),},},
	'FormatGroup':{global:{menu:_('~Group'),},},
	'FormatLegend':{global:{menu:_('Format Legend...'),},},
	'FormatLine':{global:{menu:_('L~ine...'),},},
	'FormatMajorGrid':{global:{menu:_('Format Major Grid...'),},},
	'FormatMeanValue':{global:{menu:_('Format Mean Value Line...'),},},
	'FormatMenu':{global:{menu:_('F~ormat'),},},
	'FormatMinorGrid':{global:{menu:_('Format Minor Grid...'),},},
	'FormatPaintbrush':{global:{context:_('Clone Formatting (double click for multi-selection)'),menu:_('Clone Formatting'),},text:{context:_('Clone Formatting (double click and Ctrl or Cmd to alter behavior)'),menu:_('Clone Formatting'),},},
	'FormatSelection':{global:{menu:_('Format Selection...'),},},
	'FormatSpacingMenu':{global:{menu:_('~Spacing'),},},
	'FormatStockGain':{global:{menu:_('Format Stock Gain...'),},},
	'FormatStockLoss':{global:{menu:_('Format Stock Loss...'),},},
	'FormatTextMenu':{global:{menu:_('Te~xt'),},},
	'FormatTitle':{global:{menu:_('Format Title...'),},},
	'FormatTrendline':{global:{menu:_('Format Trend Line...'),},},
	'FormatTrendlineEquation':{global:{menu:_('Format Trend Line Equation...'),},},
	'FormatWall':{global:{menu:_('Format Wall...'),},},
	'FormatXErrorBars':{global:{menu:_('Format X Error Bars...'),},},
	'FormatYErrorBars':{global:{menu:_('Format Y Error Bars...'),},},
	'FormattingMarkMenu':{global:{menu:_('Formatting Mark'),},},
	'Forward':{global:{menu:_('Bring ~Forward'),},presentation:{menu:_('Bring ~Forward'),},},
	'FourierAnalysisDialog':{spreadsheet:{menu:_('F~ourier Analysis...'),},},
	'FreezeCellsMenu':{spreadsheet:{menu:_('Freeze ~Cells'),},},
	'FreezePanes':{spreadsheet:{menu:_('Freeze ~Rows and Columns'),},},
	'FreezePanesColumn':{spreadsheet:{menu:_('Freeze First Column'),},},
	'FreezePanesRow':{spreadsheet:{menu:_('Freeze First Row'),},},
	'FullScreen':{global:{menu:_('F~ull Screen'),},},
	'FunctionDialog':{spreadsheet:{menu:_('~Function...'),},},
	'GoalSeekDialog':{spreadsheet:{menu:_('~Goal Seek...'),},},
	'Group':{global:{menu:_('~Group...'),},},
	'GroupOutlineMenu':{spreadsheet:{menu:_('~Group and Outline'),},},
	'Grow':{global:{context:_('Increase Font Size'),menu:_('Increase Size'),},},
	'HeaderAndFooter':{presentation:{menu:_('~Header and Footer...'),},},
	'HelpMenu':{global:{menu:_('~Help'),},},
	'Hide':{spreadsheet:{menu:_('~Hide Sheet'),},},
	'HideColumn':{spreadsheet:{context:_('H~ide Columns'),menu:_('~Hide'),},},
	'HideDetail':{global:{menu:_('~Hide Details'),},},
	'HideRow':{spreadsheet:{context:_('H~ide Rows'),menu:_('H~ide'),},},
	'HyperlinkDialog':{global:{context:_('Insert Hyperlink'),menu:_('~Hyperlink...'),},},
	'Hyphenate':{spreadsheet:{menu:_('~Hyphenation...'),},text:{menu:_('~Hyphenation...'),},},
	'Hyphenation':{presentation:{menu:_('~Hyphenation'),},},
	'IconSetFormatDialog':{spreadsheet:{menu:_('Icon Set...'),},},
	'IncrementIndent':{global:{context:_('Increase Indent'),menu:_('Increase Indent'),},},
	'IncrementLevel':{text:{menu:_('Promote One Level'),},},
	'IncrementSubLevels':{text:{menu:_('Promote One Level With Subpoints'),},},
	'IndexesMenu':{text:{menu:_('Table of Contents and Inde~x'),},},
	'InsertAnnotation':{global:{context:_('Insert Comment'),menu:_('Comme~nt'),},presentation:{menu:_('Comme~nt'),},spreadsheet:{context:_('Insert Co~mment'),menu:_('Comm~ent'),},},
	'InsertAuthorField':{presentation:{menu:_('~Author'),},text:{menu:_('First ~Author'),},},
	'InsertAuthoritiesEntry':{text:{menu:_('~Bibliography Entry...'),},},
	'InsertAxis':{global:{menu:_('Insert Axis'),},},
	'InsertAxisTitle':{global:{menu:_('Insert Axis Title'),},},
	'InsertBookmark':{text:{context:_('Insert Bookmark'),menu:_('Bookmar~k...'),},},
	'InsertBreak':{text:{menu:_('Manual ~Break...'),},},
	'InsertBreakMenu':{spreadsheet:{menu:_('Insert Page ~Break'),},},
	'InsertCaptionDialog':{text:{context:_('Insert Caption...'),menu:_('Caption...'),},},
	'InsertCell':{spreadsheet:{menu:_('Insert ~Cells...'),},},
	'InsertColumnBreak':{spreadsheet:{menu:_('~Column Break'),},text:{menu:_('Insert Column Break'),},},
	'InsertColumnsAfter':{presentation:{menu:_('Insert Column After'),},spreadsheet:{context:_('Insert Columns ~After'),menu:_('Columns ~After'),},text:{menu:_('Columns ~After'),},},
	'InsertColumnsBefore':{presentation:{menu:_('Insert Column Before'),},spreadsheet:{context:_('Insert Columns ~Before'),menu:_('Columns ~Before'),},text:{menu:_('Columns ~Before'),},},
	'InsertColumnsMenu':{spreadsheet:{menu:_('Insert Co~lumns'),},},
	'InsertCurrentDate':{spreadsheet:{menu:_('~Date'),},},
	'InsertCurrentTime':{spreadsheet:{menu:_('~Time'),},},
	'InsertDataLabel':{global:{menu:_('Insert Single Data Label'),},},
	'InsertDateField':{text:{menu:_('~Date'),},},
	'InsertDateFieldFix':{presentation:{menu:_('~Date (fixed)'),},},
	'InsertDateFieldVar':{presentation:{menu:_('Dat~e (variable)'),},},
	'InsertEndnote':{text:{context:_('Insert Endnote'),menu:_('~Endnote'),},},
	'InsertField':{text:{menu:_('~More Fields...'),},},
	'InsertFieldCtrl':{text:{context:_('Insert Field'),menu:_('Fiel~d'),},},
	'InsertFootnote':{text:{context:_('Insert Footnote'),menu:_('~Footnote'),},},
	'InsertGraphic':{global:{context:_('Insert Image...'),menu:_('~Image...'),},},
	'InsertHardHyphen':{global:{menu:_('Insert non-br~eaking hyphen'),},},
	'InsertHeaderFooterMenu':{text:{menu:_('He~ader and Footer'),},},
	'InsertIndexesEntry':{text:{context:_('Insert Index Entry'),menu:_('~Index Entry...'),},},
	'InsertLRM':{global:{menu:_('~Left-to-right Mark'),},},
	'InsertMajorGrid':{global:{menu:_('Insert Major Grid'),},},
	'InsertMeanValue':{global:{menu:_('Insert Mean ~Value Line'),},},
	'InsertMenu':{global:{menu:_('~Insert'),},},
	'InsertMinorGrid':{global:{menu:_('Insert Minor Grid'),},},
	'InsertMultiIndex':{text:{context:_('Insert Table of Contents, Index or Bibliography'),menu:_('Table of Contents, ~Index or Bibliography...'),},},
	'InsertNeutralParagraph':{text:{menu:_('Insert Unnumbered Entry'),},},
	'InsertNonBreakingSpace':{global:{menu:_('Insert ~non-breaking space'),},},
	'InsertObjectChart':{global:{context:_('Insert Chart'),menu:_('~Chart...'),},},
	'InsertPage':{presentation:{menu:_('New Page'),},},
	'InsertPageCountField':{text:{menu:_('Page ~Count'),},},
	'InsertPageFooter':{text:{menu:_('Foote~r'),},},
	'InsertPageHeader':{text:{menu:_('He~ader'),},},
	'InsertPageNumberField':{global:{menu:_('~Page Numbers...'),},text:{menu:_('~Page Number'),},},
	'InsertPagebreak':{text:{context:_('Insert Page Break'),menu:_('~Page Break'),},},
	'InsertPivotTable':{spreadsheet:{menu:_('~Insert or Edit...'),},},
	'InsertRLM':{global:{menu:_('~Right-to-left Mark'),},},
	'InsertReferenceField':{text:{context:_('Insert Cross-reference'),menu:_('Cross-reference...'),},},
	'InsertRemoveAxes':{global:{menu:_('Insert/Delete Axes...'),},},
	'InsertRowBreak':{spreadsheet:{menu:_('~Row Break'),},},
	'InsertRowsAfter':{presentation:{menu:_('Insert Row Below'),},spreadsheet:{context:_('Insert Rows ~Below'),menu:_('Rows ~Below'),},text:{menu:_('Rows ~Below'),},},
	'InsertRowsBefore':{presentation:{menu:_('Insert Row Above'),},spreadsheet:{context:_('Insert Rows ~Above'),menu:_('Rows ~Above'),},text:{menu:_('Rows ~Above'),},},
	'InsertRowsMenu':{spreadsheet:{menu:_('Insert ~Rows'),},},
	'InsertSection':{text:{menu:_('Se~ction...'),},},
	'InsertSlide':{presentation:{menu:_('~New Slide'),},},
	'InsertSlideField':{presentation:{menu:_('~Slide Number'),},},
	'InsertSlideTitleField':{presentation:{menu:_('Slide Tit~le'),},},
	'InsertSlidesField':{presentation:{menu:_('Slide ~Count'),},},
	'InsertSoftHyphen':{global:{menu:_('Insert s~oft Hyphen'),},},
	'InsertSymbol':{global:{context:_('Insert Special Character'),menu:_('S~pecial Character...'),},},
	'InsertTable':{presentation:{menu:_('~Table...'),},text:{menu:_('Insert ~Table...'),},},
	'InsertTimeField':{global:{menu:_('Time Field'),},text:{menu:_('~Time'),},},
	'InsertTimeFieldFix':{presentation:{menu:_('~Time (fixed)'),},},
	'InsertTimeFieldVar':{presentation:{menu:_('T~ime (variable)'),},},
	'InsertTitleField':{text:{menu:_('T~itle'),},},
	'InsertTitles':{global:{menu:_('Insert Titles...'),},},
	'InsertTopicField':{text:{menu:_('~Subject'),},},
	'InsertTrendline':{global:{menu:_('Insert Tre~nd Line...'),},},
	'InsertXErrorBars':{global:{menu:_('Insert X Error ~Bars...'),},},
	'InsertYErrorBars':{global:{menu:_('Insert Y Error ~Bars...'),},},
	'InsertZWNBSP':{global:{menu:_('No-width No ~Break'),},},
	'InsertZWSP':{global:{menu:_('No-~width Optional Break'),},},
	'Intersect':{global:{menu:_('I~ntersect'),},},
	'Italic':{global:{menu:_('Italic'),},},
	'JumpDownThisLevel':{text:{menu:_('To Next Paragraph in Level'),},},
	'JumpUpThisLevel':{text:{menu:_('To Previous Paragraph in Level'),},},
	'JustifyPara':{global:{menu:_('Justified'),},},
	'LanguageMenu':{global:{menu:_('Language'),},},
	'LanguageStatus':{global:{menu:_('Language Status'),},},
	'LayoutStatus':{presentation:{menu:_('Layout'),},},
	'LeaveGroup':{global:{menu:_('E~xit Group'),},},
	'LeftPara':{global:{context:_('Align Left'),menu:_('Left'),},},
	'Line':{global:{context:_('Insert Line'),menu:_('Line'),},},
	'LineNumberingDialog':{text:{menu:_('~Line Numbering...'),},},
	'LineSpacing':{global:{context:_('Set Line Spacing'),menu:_('Line Spacing'),},},
	'CharSpacing':{global:{context:_('Set Char Spacing'),menu:_('Char Spacing'),},},
	'MasterSlidesPanel':{presentation:{menu:_('Master Slides'),},},
	'Merge':{global:{menu:_('~Merge'),},},
	'MergeCells':{presentation:{menu:_('Merge Cells'),},spreadsheet:{menu:_('Merge Cells'),},text:{menu:_('Merge Cells'),},},
	'ModifyPage':{presentation:{menu:_('Slide ~Layout'),},},
	'Move':{spreadsheet:{menu:_('~Move or Copy Sheet...'),},},
	'CopyTab':{spreadsheet:{menu:_('Copy Sheet...'),},},
	'MoveDown':{text:{menu:_('Move Down'),},},
	'MoveDownSubItems':{text:{menu:_('Move Down with Subpoints'),},},
	'MoveUp':{text:{menu:_('Move Up'),},},
	'MoveUpSubItems':{text:{menu:_('Move Up with Subpoints'),},},
	'MovingAverageDialog':{spreadsheet:{menu:_('~Moving Average...'),},},
	'NamesMenu':{spreadsheet:{menu:_('~Named Ranges and Expressions'),},},
	'NextTrackedChange':{text:{context:_('Next Track Change'),menu:_('Next'),},},
	'NumberFormatCurrency':{spreadsheet:{context:_('Format as Currency'),menu:_('Currency'),},text:{menu:_('Number Format: Currency'),},},
	'NumberFormatDate':{spreadsheet:{context:_('Format as Date'),menu:_('Date'),},text:{menu:_('Number Format: Date'),},},
	'NumberFormatDecDecimals':{spreadsheet:{menu:_('Delete Decimal Place'),},},
	'NumberFormatDecimal':{spreadsheet:{context:_('Format as Number'),menu:_('Number'),},text:{menu:_('Number Format: Decimal'),},},
	'NumberFormatIncDecimals':{spreadsheet:{menu:_('Add Decimal Place'),},},
	'NumberFormatMenu':{spreadsheet:{menu:_('Number Format'),},},
	'NumberFormatPercent':{spreadsheet:{context:_('Format as Percent'),menu:_('Percent'),},text:{menu:_('Number Format: Percent'),},},
	'NumberFormatScientific':{spreadsheet:{menu:_('Scientific'),},text:{menu:_('Number Format: Exponential'),},},
	'NumberFormatStandard':{spreadsheet:{menu:_('General'),},text:{menu:_('Number Format: Standard'),},},
	'NumberFormatThousands':{spreadsheet:{menu:_('Thousands Separator'),},},
	'NumberFormatTime':{spreadsheet:{menu:_('Time'),},text:{menu:_('Number Format: Time'),},},
	'NumberingStart':{text:{menu:_('Restart Numbering'),},},
	'ObjectAlignLeft':{global:{menu:_('~Left'),},},
	'ObjectAlignRight':{global:{menu:_('~Right'),},},
	'ObjectBackOne':{global:{menu:_('Back One'),},},
	'ObjectForwardOne':{global:{menu:_('Forward One'),},},
	'OnlineAutoFormat':{text:{menu:_('~While Typing'),},},
	'OpenHyperlinkOnCursor':{global:{menu:_('Open Hyperlink'),},},
	'OutlineBullet':{global:{menu:_('~Bullets and Numbering...'),},},
	'OutlineLeft':{global:{menu:_('Promote'),},},
	'OutlineRight':{global:{menu:_('Demote'),},},
	'OutlineFont':{global:{menu:_('Outline'),},},
	'Overline':{global:{menu:_('Overline'),},},
	'PageDialog':{global:{menu:_('~Page...'),},text:{menu:_('~Page Style...'),},},
	'PageDown':{text:{menu:_('Next Page'),},},
	'PageFormatDialog':{spreadsheet:{context:_('Format Pa~ge...'),menu:_('~Page...'),},},
	'PageMenu':{presentation:{menu:_('~Page'),},},
	'SlideSetup':{presentation:{menu:_('Slide Properties'),},},
	'PageSetup':{presentation:{menu:_('Page Properties...'),},},
	'PageUp':{text:{menu:_('Previous Page'),},},
	'ParaLeftToRight':{global:{menu:_('Left-To-Right'),},},
	'ParaRightToLeft':{global:{menu:_('Right-To-Left'),},},
	'ParagraphDialog':{global:{menu:_('P~aragraph...'),},},
	'ParaspaceDecrease':{global:{context:_('Decrease Paragraph Spacing'),menu:_('Decrease Paragraph Spacing'),},},
	'ParaspaceIncrease':{global:{context:_('Increase Paragraph Spacing'),menu:_('Increase Paragraph Spacing'),},},
	'Paste':{global:{menu:_('~Paste'),},},
	'PickList':{global:{menu:_('~File'),},},
	'Presentation':{presentation:{menu:_('Start from ~First Slide'),},},
	'PreviousTrackedChange':{text:{context:_('Previous Track Change'),menu:_('Pr~evious'),},},
	'Print':{global:{menu:_('~Print...'),},},
	'RecalcPivotTable':{spreadsheet:{menu:_('~Refresh'),},},
	'Redo':{global:{menu:_('~Redo'),},},
	'RegressionDialog':{spreadsheet:{menu:_('~Regression...'),},},
	'RejectAllTrackedChanges':{text:{context:_('Reject All Changes'),menu:_('Reject All'),},},
	'RejectTrackedChange':{text:{context:_('Reject Change'),menu:_('Reject'),},},
	'RejectTrackedChangeToNext':{text:{context:_('Reject Track Change and select the next one'),menu:_('Reject and Move to Next'),},},
	'Remove':{spreadsheet:{menu:_('~Delete Sheet...'),},},
	'RemoveBullets':{text:{menu:_('Numbering Off'),},},
	'RemoveHyperlink':{global:{menu:_('~Remove Hyperlink'),},},
	'RemoveTableOf':{text:{menu:_('Delete index'),},},
	'RenameTable':{spreadsheet:{menu:_('Rename S~heet...'),},},
	'ReplyComment':{global:{menu:_('Reply Comment'),},},
	'ResetAllDataPoints':{global:{menu:_('Reset all Data Points'),},},
	'ResetAttributes':{global:{menu:_('~Clear Direct Formatting'),},spreadsheet:{context:_('Clear Direct Formatting'),menu:_('Clear ~Direct Formatting'),},text:{context:_('Clear Direct Formatting'),menu:_('Clear ~Direct Formatting'),},},
	'ResetDataPoint':{global:{menu:_('Reset Data Point'),},},
	'RightPara':{global:{context:_('Align Right'),menu:_('Right'),},},
	'RotateLeft':{text:{menu:_('Rotate 90° ~Left'),},},
	'RotateMenu':{global:{menu:_('Rot~ate'),},},
	'RotateRight':{text:{menu:_('Rotate 90° ~Right'),},},
	'RowOperations':{spreadsheet:{menu:_('Row'),},},
	'RunMacro':{global:{menu:_('R~un Macro...'),},},
	'SamplingDialog':{spreadsheet:{menu:_('~Sampling...'),},},
	'Save':{global:{menu:_('~Save'),},},
	'SaveAs':{global:{menu:_('Save ~As...'),},},
	'SearchDialog':{global:{menu:_('Find and Rep~lace...'),},},
	'SelectAll':{global:{menu:_('Select ~All'),},},
	'SelectBackground':{presentation:{menu:_('Set Background Image...'),},},
	'SelectObject':{global:{menu:_('Select'),},},
	'SelectTable':{presentation:{context:_('Select Table'),menu:_('~Select Table'),},text:{context:_('Select Table'),menu:_('~Table'),},},
	'SendToBack':{global:{menu:_('~Send to Back'),},},
	'SetAnchorAtChar':{text:{menu:_('To ~Character'),},},
	'SetAnchorToCell':{spreadsheet:{menu:_('To ~Cell'),},},
	'SetAnchorToCellResize':{spreadsheet:{menu:_('To Cell (~resize with cell)'),},},
	'SetAnchorToChar':{text:{menu:_('As C~haracter'),},},
	'SetAnchorToFrame':{text:{menu:_('To ~Frame'),},},
	'SetAnchorToPage':{spreadsheet:{menu:_('To P~age'),},text:{menu:_('To P~age'),},},
	'SetAnchorToPara':{text:{menu:_('To ~Paragraph'),},},
	'SetBorderStyle':{global:{menu:_('Borders (Shift to overwrite)'),},},
	'SetDefault':{global:{context:_('Clear Direct Formatting'),menu:_('Clear ~Direct Formatting'),},},
	'SetLanguageAllTextMenu':{global:{menu:_('For All Text'),},},
	'SetLanguageParagraphMenu':{global:{menu:_('For Paragraph'),},},
	'SetLanguageSelectionMenu':{global:{menu:_('For Selection'),},},
	'SetObjectToBackground':{global:{menu:_('To Background'),},},
	'SetObjectToForeground':{global:{menu:_('To Foreground'),},},
	'SetOptimalColumnWidth':{presentation:{menu:_('Optimal Column Width'),},spreadsheet:{menu:_('~Optimal Width...'),},text:{menu:_('Optimal Column Width'),},},
	'SetOptimalRowHeight':{presentation:{menu:_('Optimal Row Height'),},spreadsheet:{menu:_('~Optimal Height...'),},text:{menu:_('Optimal Row Height'),},},
	'Shadowed':{global:{context:_('Toggle Shadow'),menu:_('Shadow'),},},
	'ShapesMenu':{global:{menu:_('~Shape'),},},
	'SheetMenu':{spreadsheet:{menu:_('~Sheet'),},},
	'Show':{spreadsheet:{menu:_('~Show Sheet...'),},},
	'ShowColumn':{spreadsheet:{context:_('S~how Columns'),menu:_('~Show'),},},
	'ShowDetail':{global:{menu:_('~Show Details'),},},
	'ShowResolvedAnnotations':{text:{menu:_('Resolved Comments'),},},
	'ShowRow':{spreadsheet:{context:_('Sho~w Rows'),menu:_('~Show'),},},
	'ShowTrackedChanges':{text:{context:_('Show Track Changes'),menu:_('~Show'),},},
	'Shrink':{global:{context:_('Decrease Font Size'),menu:_('Decrease Size'),},},
	'Sidebar':{global:{menu:_('Sidebar'),},},
	'SlideChangeWindow':{presentation:{menu:_('Slide Transition'),},},
	'SlideMasterPage':{presentation:{menu:_('~Master Slide'),},},
	'SlideMenu':{presentation:{menu:_('S~lide'),},},
	'SmallCaps':{global:{menu:_('Small capitals'),},},
	'SortAscending':{spreadsheet:{menu:_('Sort Ascending'),},},
	'SortDescending':{spreadsheet:{menu:_('Sort Descending'),},},
	'SpacePara1':{global:{menu:_('Line Spacing: 1'),},},
	'SpacePara15':{global:{menu:_('Line Spacing: 1.5'),},},
	'SpacePara2':{global:{menu:_('Line Spacing: 2'),},},
	'Spacing':{global:{context:_('Set Character Spacing'),menu:_('Character Spacing'),},},
	'SpellCheckApplySuggestion':{global:{menu:_('Apply Suggestion'),},},
	'SpellCheckIgnore':{global:{menu:_('Ignore'),},},
	'SpellCheckIgnoreAll':{global:{menu:_('IgnoreAll'),},},
	'SpellDialog':{global:{menu:_('~Spelling...'),},},
	'SpellOnline':{global:{context:_('Toggle Automatic Spell Checking'),menu:_('~Automatic Spell Checking'),},},
	'SpellingAndGrammarDialog':{global:{context:_('Check Spelling'),menu:_('~Spelling...'),},},
	'SplitCell':{presentation:{menu:_('Split Cells'),},spreadsheet:{menu:_('Split Cells'),},text:{menu:_('Split Cells...'),},},
	'SplitTable':{text:{menu:_('Split Table...'),},},
	'StatisticsMenu':{spreadsheet:{menu:_('Statistics'),},},
	'Strikeout':{global:{menu:_('Strikethrough'),},},
	'StyleUpdateByExample':{global:{menu:_('Update'),},},
	'SubScript':{global:{menu:_('Subscript'),},text:{menu:_('Subscript'),},},
	'Substract':{global:{menu:_('~Subtract'),},},
	'SuperScript':{global:{menu:_('Superscript'),},text:{menu:_('Superscript'),},},
	'TTestDialog':{spreadsheet:{menu:_('Paired ~t-test...'),},},
	'TableDeleteMenu':{global:{menu:_('~Delete'),},},
	'TableDialog':{presentation:{context:_('Ta~ble Properties...'),menu:_('~Properties...'),},text:{context:_('~Table Properties...'),menu:_('~Properties...'),},},
	'TableInsertMenu':{global:{menu:_('~Insert'),},},
	'TableMenu':{global:{menu:_('T~able'),},},
	'TableNumberFormatDialog':{text:{menu:_('Number Format...'),},},
	'TableSelectMenu':{text:{menu:_('~Select'),},},
	'TableSort':{presentation:{menu:_('So~rt...'),},text:{menu:_('So~rt...'),},},
	'TaskPaneInsertPage':{presentation:{menu:_('Insert Slide'),},},
	'Text':{global:{context:_('Insert Text Box'),menu:_('~Text Box'),},},
	'TextAlign':{global:{menu:_('Align Tex~t'),},},
	'TextWrap':{text:{menu:_('Text Wrap...'),},},
	'ThesaurusDialog':{global:{menu:_('~Thesaurus...'),},text:{menu:_('~Thesaurus...'),},},
	'TitlePageDialog':{text:{menu:_('Title Page...'),},},
	'ToggleMergeCells':{spreadsheet:{menu:_('M~erge and Center Cells'),},},
	'ToolsMenu':{global:{menu:_('~Tools'),},},
	'TrackChanges':{text:{context:_('Record Track Changes'),menu:_('~Record'),},},
	'TransformDialog':{global:{menu:_('Position and Si~ze...'),},},
	'Underline':{global:{menu:_('Underline'),},},
	'UnderlineDouble':{global:{menu:_('Double Underline'),},},
	'Undo':{global:{menu:_('~Undo'),},},
	'Ungroup':{global:{menu:_('~Ungroup...'),},},
	'UpSearch':{global:{menu:_('Find Previous'),},},
	'UpdateAll':{text:{menu:_('~Update All'),},},
	'UpdateCurIndex':{text:{context:_('Update index'),menu:_('Current ~Index'),},},
	'Validation':{spreadsheet:{menu:_('~Validity...'),},},
	'VerticalText':{global:{context:_('Insert Vertical Text'),menu:_('Vertical Text'),},},
	'View3D':{global:{menu:_('~3D View...'),},},
	'ViewDataSourceBrowser':{global:{menu:_('~Data Sources'),},},
	'ViewMenu':{global:{menu:_('~View'),},},
	'Watermark':{text:{menu:_('Watermark...'),},},
	'WordCountDialog':{text:{menu:_('~Word Count...'),},},
	'WrapAnchorOnly':{text:{menu:_('~First Paragraph'),},},
	'WrapContour':{text:{menu:_('~Contour'),},},
	'WrapIdeal':{text:{menu:_('~Optimal'),},},
	'WrapLeft':{text:{menu:_('Before'),},},
	'WrapMenu':{text:{menu:_('~Wrap'),},},
	'WrapOff':{text:{menu:_('None'),},},
	'WrapOn':{text:{menu:_('~Parallel'),},},
	'WrapRight':{text:{menu:_('After'),},},
	'WrapText':{spreadsheet:{menu:_('Wrap Text'),},},
	'WrapThrough':{text:{menu:_('~Through'),},},
	'WrapThroughTransparencyToggle':{text:{menu:_('In ~Background'),},},
	'XLineColor':{global:{menu:_('Line Color'),},},
	'ZTestDialog':{spreadsheet:{menu:_('~Z-test...'),},},
	'ZoomMinus':{global:{menu:_('Zoom Out'),},},
	'ZoomPlus':{global:{menu:_('Zoom In'),},},
};

window._UNO = function(string, component, isContext) {
	var command = string.substr(5);
	var context = 'menu';
	if (isContext === true) {
		context = 'context';
	}
	var entry = unoCommandsArray[command];
	if (entry === undefined) {
		return command;
	}
	var componentEntry = entry[component];
	if (componentEntry === undefined) {
		componentEntry = entry['global'];
		if (componentEntry === undefined) {
			return command;
		}
	}
	var text = componentEntry[context];
	if (text === undefined) {
		text = componentEntry['menu'];
		if (text === undefined) {
			return command;
		}
	}

	return this.removeAccessKey(text);
}

window.removeAccessKey = function(text) {
	// Remove access key markers from translated strings
	// 1. access key in parenthesis in case of non-latin scripts
	text = text.replace(/\(~[A-Za-z]\)/, '');
	// 2. remove normal access key
	text = text.replace('~', '');

	return text;
}
