#!/bin/bash

# utilities
TR='tr'
WC='wc'
PS='ps'
SED='sed'
TOP='top'
GREP='grep'
PSTREE='pstree'

# log pid file
PIDLOG="/tmp/loolwsd.pid"

# print error message
log_failure_msg () {
  if [ -n "${1:-}" ]; then
    /bin/echo "$@" || true
  fi
}

# checking ... print lines matching a pattern utility
if ! echo a | $GREP -E '(a|b)' >/dev/null 2>&1; then
  log_failure_msg "$0: error: $GREP utility not found."
fi

# checking ... word count utility
if ! $WC --version >/dev/null 2>&1; then
  log_failure_msg "$0: error: $WC utility not found."
fi

# checking ... stream editor utility
if ! $SED --version >/dev/null 2>&1; then
  log_failure_msg "$0: error: $SED utility not found."
fi

# checking ... delete characters utility
if ! $TR --version >/dev/null 2>&1; then
  log_failure_msg "$0: error: $TR utility not found."
fi

# checking ... display a tree of processes utility
if ! $PSTREE --version >/dev/null 2>&1; then
  log_failure_msg "$0: error: $PSTREE utility not found."
fi

# checking ... report a snapshot of the current processes utility.
if ! $PS --version >/dev/null 2>&1; then
  log_failure_msg "$0: error: $PS utility not found."
fi

# checking ... report a snapshot of the current processes utility.
if ! $TOP -v >/dev/null 2>&1; then
  log_failure_msg "$0: error: $TOP utility not found."
fi

# checking pid log file.
if [ ! -f $PIDLOG ]; then
	log_failure_msg "$0: error: $PIDLOG file not found."
	exit 1;
fi

# get the loolwsd process id.
LOOLWSD_PID=$(cat $PIDLOG);

# checking if loolwsd is running.
if ! $PS -p $LOOLWSD_PID > /dev/null; then
	log_failure_msg "$0: error: loolwsd is not running."
	exit 1;
fi

# display a tree of processes.
$PSTREE -a -c -h -A -p $LOOLWSD_PID;

# get the number of running processes.
LOOLWSD=$($PSTREE -a -h -A -p $LOOLWSD_PID | $SED -e "s/\`//g" | $TR -d ' |-' | $GREP -o '^loolwsd,' | $WC -l);

# get the number of running processes.
LOOLBROKER=$($PSTREE -a -h -A -p $LOOLWSD_PID | $SED -e "s/\`//g" | $TR -d ' |-' | $GREP -o '^loolbroker,' | $WC -l);

# get the number of running processes.
LOOLKIT=$($PSTREE -a -h -A -p $LOOLWSD_PID | $SED -e "s/\`//g" | $TR -d ' |-' | $GREP -o '^libreofficekit,' | $WC -l);

# get the number of running threads.
LOOLWSD_THREADS=$($PSTREE -a -h -A -p $LOOLWSD_PID | $GREP -o '{.*}' | $WC -l);

# get the number of running client socket.
LOOLWSD_CLIENT=$($PSTREE -a -h -A -p $LOOLWSD_PID | $GREP -o '{client_socket}' | $WC -l);

# get the number of running client socket.
LOOLWSD_PRISIONER=$($PSTREE -a -h -A -p $LOOLWSD_PID | $GREP -o '{prision_socket}' | $WC -l);

# get the number of processes swapped out.
LOOLKIT_SWAPPEDOUT=$($PSTREE -a -h -A -p $LOOLWSD_PID | $GREP -o '(.*)' | $WC -l);

# display report stats
printf "\n %-10s\n" "LOOLWSD STATS";
printf "==========================\n";
printf " %-10s %d\n" "Running loolwsd process:" "$LOOLWSD";
printf " %-10s %d\n" "Running loolwsd threads:" "$LOOLWSD_THREADS";
printf " %-10s %d\n" "Socket Client   threads:" "$LOOLWSD_CLIENT";
printf " %-10s %d\n" "Socket Prision  threads:" "$LOOLWSD_PRISIONER";
printf " %-10s %d\n\n" "Process ... swapped out:" "$LOOLKIT_SWAPPEDOUT";
$TOP -bn 1 -p $LOOLWSD_PID | $GREP -E 'loolwsd|COMMAND'
printf "\n %-10s %d\n" "Running loolbroker process:" "$LOOLBROKER";
$TOP -bn 1 | $GREP -E 'loolbroker|COMMAND'
printf "\n%-10s %d\n" "Running LibreOfficeKit process:" "$LOOLKIT";
$TOP -bn 1 | $GREP -E 'libreofficekit|COMMAND'

