{{- if .Values.nginxDeny.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "collabora-online.fullname" . }}-nginxdeny
  labels:
    {{- include "collabora-online.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events { }
    http {
        server {
            listen 80 default_server;
            location / {
                return 403;
            }
        }
    }
{{- end }}
