{{- if .Values.nginxDeny.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "collabora-online.fullname" . }}-nginxdeny
  labels:
    {{- include "collabora-online.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginxDeny.replicaCount }}
  selector:
    matchLabels:
      {{- include "collabora-online.selectorLabels" . | nindent 6 }}
      type: nginxdeny
  template:
    metadata:
      labels:
        {{- include "collabora-online.selectorLabels" . | nindent 8 }}
        type: nginxdeny
    spec:
      serviceAccountName: {{ include "collabora-online.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.nginxDeny.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-nginxdeny
          securityContext:
            {{- toYaml .Values.nginxDeny.securityContext | nindent 12 }}
          image: "{{ .Values.nginxDeny.image.repository }}:{{ .Values.nginxDeny.image.tag }}"
          imagePullPolicy: {{ .Values.nginxDeny.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nginxDeny.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.nginxDeny.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      {{- with .Values.nginxDeny.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginxDeny.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginxDeny.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "collabora-online.fullname" . }}-nginxdeny
{{- end }}
