// Don't modify, generated using unocommands.py

var unoCommandsArray = {
	AcceptAllTrackedChanges:{text:{menu:_('Accept All'),},},
	AcceptTrackedChanges:{text:{menu:_('~Manage...'),},},
	AnchorMenu:{global:{menu:_('Anc~hor'),},},
	ArrangeFrameMenu:{text:{menu:_('Arrange'),},},
	ArrangeMenu:{global:{menu:_('A~rrange'),},presentation:{menu:_('~Arrange'),},},
	Bold:{global:{menu:_('Bold'),},},
	BringToFront:{global:{menu:_('~Bring to Front'),},},
	ChangeCaseRotateCase:{global:{menu:_('Cycle Case'),},},
	ChangeCaseToLower:{global:{menu:_('~lowercase'),},},
	ChangeCaseToSentenceCase:{global:{menu:_('~Sentence case'),},},
	ChangeCaseToTitleCase:{global:{menu:_('~Capitalize Every Word'),},},
	ChangeCaseToToggleCase:{global:{menu:_('~tOGGLE cASE'),},},
	ChangeCaseToUpper:{global:{menu:_('~UPPERCASE'),},},
	ChangesMenu:{global:{menu:_('Track Chan~ges'),},},
	ClearOutline:{global:{menu:_('~Remove Outline'),},},
	CommonAlignBottom:{global:{menu:_('Bottom'),},},
	CommonAlignHorizontalCenter:{global:{menu:_('Centered'),},},
	CommonAlignJustified:{global:{menu:_('Justified'),},},
	CommonAlignLeft:{global:{menu:_('Left'),},},
	CommonAlignRight:{global:{menu:_('Right'),},},
	CommonAlignTop:{global:{menu:_('Top'),},},
	CommonAlignVerticalCenter:{global:{menu:_('Center'),},},
	ContinueNumbering:{text:{menu:_('Continue previous numbering'),},},
	ControlCodes:{text:{menu:_('For~matting Marks'),},},
	Copy:{global:{menu:_('Cop~y'),},},
	CopyHyperlinkLocation:{text:{menu:_('Copy Link Location'),},},
	Cut:{global:{menu:_('~Cut'),},},
	DataFilterAutoFilter:{spreadsheet:{menu:_('Auto~Filter'),},},
	DataFilterHideAutoFilter:{spreadsheet:{menu:_('~Hide AutoFilter'),},},
	DataFilterRemoveFilter:{spreadsheet:{menu:_('~Reset Filter'),},},
	DataFilterSpecialFilter:{spreadsheet:{menu:_('~Advanced Filter...'),},},
	DataFilterStandardFilter:{spreadsheet:{menu:_('~Standard Filter...'),},},
	DataMenu:{spreadsheet:{menu:_('~Data'),},},
	DataSort:{spreadsheet:{menu:_('~Sort...'),},},
	DecrementIndent:{global:{menu:_('Decrease Indent'),},},
	DecrementLevel:{text:{menu:_('Demote One Level'),},},
	DecrementSubLevels:{text:{menu:_('Demote One Level With Subpoints'),},},
	DefaultBullet:{global:{menu:_('~Bulleted List'),},},
	DefaultNumbering:{global:{menu:_('~Numbered List'),},},
	DeleteAllNotes:{global:{menu:_('Delete All Comments'),},},
	DeleteAuthor:{global:{menu:_('Delete All Comments by This Author'),},},
	DeleteColumns:{presentation:{context:_('Delete Column'),menu:_('~Columns'),},spreadsheet:{menu:_('Delete Columns'),},text:{menu:_('~Columns'),},},
	DeleteComment:{global:{menu:_('Delete Comment'),},},
	DeleteRows:{presentation:{context:_('Delete Row'),menu:_('~Rows'),},spreadsheet:{menu:_('Delete Rows'),},text:{menu:_('~Rows'),},},
	DeleteSlide:{presentation:{menu:_('D~elete Slide'),},},
	DeleteTable:{text:{menu:_('~Table'),},},
	DuplicateSlide:{presentation:{menu:_('Duplicate ~Slide'),},},
	EditMenu:{global:{menu:_('~Edit'),},},
	EditStyle:{global:{menu:_('~Edit Style...'),},presentation:{menu:_('E~dit Style...'),},},
	EntireCell:{text:{menu:_('C~ell'),},},
	EntireColumn:{presentation:{menu:_('~Columns'),},text:{menu:_('~Column'),},},
	EntireRow:{presentation:{menu:_('~Rows'),},text:{menu:_('~Row'),},},
	FilterMenu:{spreadsheet:{menu:_('More ~Filters'),},},
	FontDialog:{global:{menu:_('Character...'),},},
	FormatBulletsMenu:{global:{menu:_('Lis~ts'),},},
	FormatCellDialog:{spreadsheet:{context:_('~Format Cells...'),menu:_('Ce~lls...'),},},
	FormatMenu:{global:{menu:_('F~ormat'),},},
	FormatSpacingMenu:{global:{menu:_('~Spacing'),},},
	FormatTextMenu:{global:{menu:_('Te~xt'),},},
	FormattingMarkMenu:{global:{menu:_('Formatting Mark'),},},
	FullScreen:{global:{menu:_('F~ull Screen'),},},
	Group:{global:{menu:_('~Group...'),},},
	GroupOutlineMenu:{spreadsheet:{menu:_('~Group and Outline'),},},
	Grow:{global:{menu:_('Increase Size'),},},
	HelpMenu:{global:{menu:_('~Help'),},},
	HideDetail:{global:{menu:_('~Hide Details'),},},
	HyperlinkDialog:{global:{menu:_('~Link...'),},},
	IncrementIndent:{global:{menu:_('Increase Indent'),},},
	IncrementLevel:{text:{menu:_('Promote One Level'),},},
	IncrementSubLevels:{text:{menu:_('Promote One Level With Subpoints'),},},
	InsertAnnotation:{global:{menu:_('Comme~nt'),},presentation:{menu:_('Comme~nt'),},spreadsheet:{menu:_('Comm~ent'),},},
	InsertColumnBreak:{spreadsheet:{menu:_('~Column Break'),},text:{menu:_('Insert Column Break'),},},
	InsertColumns:{presentation:{menu:_('Insert Column'),},spreadsheet:{menu:_('Columns ~Left'),},text:{menu:_('Insert Column'),},},
	InsertColumnsAfter:{presentation:{menu:_('Insert Column Right'),},spreadsheet:{context:_('Insert Columns ~Right'),menu:_('Columns ~Right'),},text:{menu:_('Columns R~ight'),},},
	InsertColumnsBefore:{presentation:{menu:_('Insert Column Left'),},spreadsheet:{context:_('Insert Columns ~Left'),menu:_('Columns ~Left'),},text:{menu:_('Columns ~Left'),},},
	InsertEndnote:{text:{menu:_('~Endnote'),},},
	InsertFootnote:{text:{menu:_('~Footnote'),},},
	InsertGraphic:{global:{menu:_('~Image...'),},},
	InsertHardHyphen:{global:{menu:_('Non-br~eaking hyphen'),},},
	InsertIndexesEntry:{text:{menu:_('~Index Entry...'),},},
	InsertLRM:{global:{menu:_('~Left-to-right mark'),},},
	InsertMenu:{global:{menu:_('~Insert'),},},
	InsertNeutralParagraph:{text:{menu:_('Insert Unnumbered Entry'),},},
	InsertNonBreakingSpace:{global:{menu:_('~Non-breaking space'),},},
	InsertPagebreak:{text:{menu:_('~Page Break'),},},
	InsertRLM:{global:{menu:_('~Right-to-left mark'),},},
	InsertRows:{presentation:{menu:_('Insert Row'),},spreadsheet:{menu:_('Rows ~Above'),},text:{menu:_('Insert Row'),},},
	InsertRowsAfter:{presentation:{menu:_('Insert Row Below'),},spreadsheet:{context:_('Insert Rows ~Below'),menu:_('Rows ~Below'),},text:{menu:_('Rows ~Below'),},},
	InsertRowsBefore:{presentation:{menu:_('Insert Row Above'),},spreadsheet:{context:_('Insert Rows ~Above'),menu:_('Rows ~Above'),},text:{menu:_('Rows ~Above'),},},
	InsertSlide:{presentation:{menu:_('New Slid~e'),},},
	InsertSoftHyphen:{global:{menu:_('S~oft hyphen'),},},
	InsertSymbol:{global:{menu:_('S~pecial Character...'),},},
	InsertZWNBSP:{global:{menu:_('No-width no ~break'),},},
	InsertZWSP:{global:{menu:_('No-~width optional break'),},},
	Italic:{global:{menu:_('Italic'),},},
	JumpDownThisLevel:{text:{menu:_('To Next Paragraph in Level'),},},
	JumpUpThisLevel:{text:{menu:_('To Previous Paragraph in Level'),},},
	MergeCells:{presentation:{menu:_('Merge Cells'),},spreadsheet:{menu:_('Merge Cells'),},text:{menu:_('Merge Cells'),},},
	MoveDown:{text:{menu:_('Move Down'),},},
	MoveDownSubItems:{text:{menu:_('Move Down with Subpoints'),},},
	MoveUp:{text:{menu:_('Move Up'),},},
	MoveUpSubItems:{text:{menu:_('Move Up with Subpoints'),},},
	NextTrackedChange:{text:{menu:_('Next'),},},
	NumberingStart:{text:{menu:_('Restart Numbering'),},},
	ObjectBackOne:{global:{menu:_('Back One'),},},
	ObjectForwardOne:{global:{menu:_('Forward One'),},},
	OpenHyperlinkOnCursor:{global:{menu:_('Open Link'),},},
	OutlineBullet:{global:{menu:_('~Bullets and Numbering...'),},},
	OutlineFont:{global:{menu:_('Outline'),},},
	Overline:{global:{menu:_('Overline'),},},
	ParaLeftToRight:{global:{menu:_('Left-To-Right'),},},
	ParaRightToLeft:{global:{menu:_('Right-To-Left'),},},
	ParagraphDialog:{global:{menu:_('P~aragraph...'),},},
	ParaspaceDecrease:{global:{menu:_('Decrease Paragraph Spacing'),},},
	ParaspaceIncrease:{global:{menu:_('Increase Paragraph Spacing'),},},
	Paste:{global:{menu:_('~Paste'),},},
	PasteSpecialMenu:{text:{menu:_('Paste ~Special'),},},
	PasteUnformatted:{global:{context:_('~Unformatted Text'),menu:_('Paste Unformatted Text'),},},
	PickList:{global:{menu:_('~File'),},},
	PreviousTrackedChange:{text:{menu:_('Pr~evious'),},},
	Print:{global:{menu:_('~Print...'),},},
	RecalcPivotTable:{spreadsheet:{menu:_('~Refresh'),},},
	Redo:{global:{menu:_('~Redo'),},},
	RejectAllTrackedChanges:{text:{menu:_('Reject All'),},},
	RemoveHyperlink:{text:{menu:_('Remove Link'),},},
	RemoveTableOf:{text:{menu:_('Delete index'),},},
	ReplyComment:{global:{menu:_('Reply Comment'),},},
	ResetAttributes:{global:{menu:_('~Clear Direct Formatting'),},spreadsheet:{menu:_('Clear ~Direct Formatting'),},text:{menu:_('Clear ~Direct Formatting'),},},
	RotateLeft:{text:{menu:_('Rotate 90° ~Left'),},},
	RotateMenu:{global:{menu:_('Rot~ate'),},},
	RotateRight:{text:{menu:_('Rotate 90° ~Right'),},},
	Save:{global:{menu:_('~Save'),},},
	SaveAs:{global:{menu:_('Save ~As...'),},},
	SearchDialog:{global:{menu:_('Find & Rep~lace...'),},},
	SelectAll:{global:{menu:_('Select ~All'),},},
	SelectTable:{presentation:{menu:_('~Table'),},text:{menu:_('~Table'),},},
	SendToBack:{global:{menu:_('~Send to Back'),},},
	SetAnchorAtChar:{text:{menu:_('To ~Character'),},},
	SetAnchorToChar:{text:{menu:_('As C~haracter'),},},
	SetAnchorToFrame:{text:{menu:_('To ~Frame'),},},
	SetAnchorToPage:{spreadsheet:{menu:_('To P~age'),},text:{menu:_('To P~age'),},},
	SetAnchorToPara:{text:{menu:_('To ~Paragraph'),},},
	SetOptimalColumnWidth:{spreadsheet:{menu:_('~Optimal Width...'),},text:{menu:_('Optimal Column Width'),},},
	SetOptimalRowHeight:{spreadsheet:{menu:_('~Optimal Height...'),},text:{menu:_('Optimal Row Height'),},},
	Shadowed:{global:{menu:_('Shadow'),},},
	SheetMenu:{spreadsheet:{menu:_('~Sheet'),},},
	ShowDetail:{global:{menu:_('~Show Details'),},},
	ShowTrackedChanges:{text:{menu:_('~Show'),},},
	Shrink:{global:{menu:_('Decrease Size'),},},
	SlideMenu:{presentation:{menu:_('S~lide'),},},
	SmallCaps:{global:{menu:_('Small capitals'),},},
	SortAscending:{spreadsheet:{menu:_('Sort Ascending'),},},
	SortDescending:{spreadsheet:{menu:_('Sort Descending'),},},
	SpacePara1:{global:{menu:_('Line Spacing: 1'),},},
	SpacePara15:{global:{menu:_('Line Spacing: 1.5'),},},
	SpacePara2:{global:{menu:_('Line Spacing: 2'),},},
	SpellOnline:{global:{menu:_('~Automatic Spell Checking'),},},
	SpellingAndGrammarDialog:{global:{menu:_('~Spelling and Grammar...'),},},
	SplitCell:{presentation:{menu:_('Split Cells'),},spreadsheet:{menu:_('Split Cells'),},text:{menu:_('Split Cells...'),},},
	Strikeout:{global:{menu:_('Strikethrough'),},},
	SubScript:{global:{menu:_('Subscript'),},text:{menu:_('Subscript'),},},
	SuperScript:{global:{menu:_('Superscript'),},text:{menu:_('Superscript'),},},
	TableDeleteMenu:{text:{menu:_('~Delete'),},},
	TableDialog:{presentation:{menu:_('Ta~ble Properties...'),},text:{menu:_('~Properties...'),},},
	TableInsertMenu:{text:{menu:_('~Insert'),},},
	TableMenu:{text:{menu:_('T~able'),},},
	TableSelectMenu:{text:{menu:_('~Select'),},},
	TextAlign:{global:{menu:_('Alig~n'),},},
	ToolsMenu:{global:{menu:_('~Tools'),},},
	TrackChanges:{text:{menu:_('~Record'),},},
	Underline:{global:{menu:_('Underline'),},},
	UnderlineDouble:{presentation:{menu:_('Double Underline '),},spreadsheet:{menu:_('Underline: Double'),},text:{menu:_('Double Underline '),},},
	Undo:{global:{menu:_('~Undo'),},},
	Ungroup:{global:{menu:_('~Ungroup...'),},},
	UpdateCurIndex:{text:{context:_('Update index'),menu:_('Current ~Index'),},},
	ViewMenu:{global:{menu:_('~View'),},},
	WordCountDialog:{text:{menu:_('~Word Count'),},},
	WrapAnchorOnly:{text:{menu:_('~First Paragraph'),},},
	WrapContour:{text:{menu:_('~Contour'),},},
	WrapIdeal:{text:{menu:_('~Optimal Page Wrap'),},},
	WrapLeft:{text:{menu:_('Wrap Left'),},},
	WrapMenu:{text:{menu:_('~Wrap'),},},
	WrapOff:{text:{menu:_('Wrap Off'),},},
	WrapOn:{text:{menu:_('~Page Wrap'),},},
	WrapRight:{text:{menu:_('Wrap Right'),},},
	WrapThrough:{text:{menu:_('~Wrap Through'),},},
	WrapThroughTransparent:{text:{menu:_('In ~Background'),},},
	ZoomMinus:{global:{menu:_('Zoom Out'),},},
	ZoomPlus:{global:{menu:_('Zoom In'),},},
};

global._UNO = function(string, component, isContext) {
	var command = string.substr(5);
	var context = 'menu';
	if (isContext === true) {
		context = 'context';
	}
	var entry = unoCommandsArray[command];
	if (entry === undefined) {
		return command;
	}
	var componentEntry = entry[component];
	if (componentEntry === undefined) {
		componentEntry = entry['global'];
		if (componentEntry === undefined) {
			return command;
		}
	}
	var text = componentEntry[context];
	if (text === undefined) {
		text = componentEntry['menu'];
		if (text === undefined) {
			return command;
		}
	}

	return text.replace('~', '');
}
