blank_issues_enabled: false
contact_links:
    - name: Question
      url: https://forum.collaboraonline.com/
      about: Ask your questions, find the answer, on our forum …
    - name: Customer or partner issue
      url: https://www.collaboraoffice.com/partner-client-portal/
      about: If you are a Collabora Online customer or partner, please submit your issue directly in the Customer and Partner portal so that our engineers can act on it more quickly.

