{{- if .Values.deployment.customFonts.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "collabora-online.fullname" . }}-custom-fonts
  labels:
    {{- include "collabora-online.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes: [ "{{ .Values.deployment.customFonts.pvc.accessMode }}" ]
  resources:
    requests:
      storage: {{ .Values.deployment.customFonts.pvc.size }}
  {{- if .Values.deployment.customFonts.pvc.storageClassName -}}
  storageClassName: {{ .Values.deployment.customFonts.pvc.storageClassName }}
  {{- end }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "collabora-online.fullname" . }}-custom-fonts
  labels:
    {{- include "collabora-online.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  restartPolicy: Never
  containers:
    - name: {{ .Chart.Name }}-custom-fonts
      securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
      image: "{{ .Values.deployment.customFonts.image.repository }}:{{ .Values.deployment.customFonts.image.tag }}"
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /mnt/fonts
          name: fonts
  volumes:
    - name: fonts
      persistentVolumeClaim:
        claimName: {{ include "collabora-online.fullname" . }}-custom-fonts
{{- end }}
