{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "collabora-online.fullname" . }}
  labels:
    {{- include "collabora-online.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "collabora-online.selectorLabels" . | nindent 6 }}

  policyTypes:
    {{- if .Values.networkPolicy.ingress }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress }}
    - Egress
    {{- end }}

  {{- if .Values.networkPolicy.ingress }}
  ingress:
    - from:
      {{- range .Values.networkPolicy.ingress }}
      {{- if .ipBlock }}
      - ipBlock:
          cidr: {{ .ipBlock.cidr }}
          {{- if .ipBlock.except }}
          except:
            {{- range .ipBlock.except }}
            - {{ . }}
            {{- end }}
          {{- end }}
      {{- end }}

      {{- if .namespaceSelector }}
      - namespaceSelector:
          matchLabels:
            {{- range $key, $value := .namespaceSelector.matchLabels }}
            {{ $key }}: {{ $value }}
            {{- end }}
          {{- if .namespaceSelector.matchExpressions }}
          matchExpressions:
            {{- range .namespaceSelector.matchExpressions }}
            - key: {{ .key }}
              operator: {{ .operator }}
              {{- if .values }}
              values:
                {{- range .values }}
                - {{ . }}
                {{- end }}
              {{- end }}
            {{- end }}
        {{- end }}
      {{- end }}

      {{- if .podSelector }}
      - podSelector:
          matchLabels:
            {{- range $key, $value := .podSelector.matchLabels }}
            {{ $key }}: {{ $value }}
            {{- end }}
          {{- if .podSelector.matchExpressions }}
          matchExpressions:
            {{- range .podSelector.matchExpressions }}
            - key: {{ .key }}
              operator: {{ .operator }}
              {{- if .values }}
              values:
                {{- range .values }}
                - {{ . }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
      {{- end }}

      {{- if .ports }}
      ports:
      {{- range .ports }}
      - protocol: {{ .protocol }}
        port: {{ .port }}
      {{- end }}
      {{- end }}

      {{- end }}
  {{- end }}

  {{- if .Values.networkPolicy.egress }}
  egress:
    - to:
      {{- range .Values.networkPolicy.egress }}
      {{- if .ipBlock }}
      - ipBlock:
          cidr: {{ .ipBlock.cidr }}
          {{- if .ipBlock.except }}
          except:
            {{- range .ipBlock.except }}
            - {{ . }}
            {{- end }}
          {{- end }}
      {{- end }}

      {{- if .ports }}
      ports:
      {{- range .ports }}
      - protocol: {{ .protocol }}
        port: {{ .port }}
      {{- end }}
      {{- end }}


      {{- end }}
  {{- end }}

{{- end }}
