{{- if .Values.installCOOLSeccompProfile }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "collabora-online.fullname" . }}-seccomp-profile-installer
  labels:
    {{- include "collabora-online.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ include "collabora-online.fullname" . }}-seccomp-installer
  template:
    metadata:
      labels:
        name: {{ include "collabora-online.fullname" . }}-seccomp-installer
    spec:
      serviceAccountName: {{ include "collabora-online.daemonServiceAccountName" . }}
      containers:
      - name: installer
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          if [ ! -f /host-seccomp/cool-seccomp-profile.json ]; then
            wget -O /host-seccomp/cool-seccomp-profile.json \
              https://raw.githubusercontent.com/CollaboraOnline/online/master/docker/cool-seccomp-profile.json
            echo "Profile installed on $(hostname)"
          else
            echo "Profile already exists on $(hostname)"
          fi
          sleep infinity
        securityContext:
          privileged: true
        volumeMounts:
        - name: seccomp-profiles
          mountPath: /host-seccomp
      volumes:
      - name: seccomp-profiles
        hostPath:
          path: /var/lib/kubelet/seccomp
          type: DirectoryOrCreate
      tolerations:
      - operator: Exists  # Run on all nodes regardless of taints
{{- end }}

