{{- if not (.Values.collabora.existingSecret).enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collabora-online.fullname" . }}
  labels:
    {{- include "collabora-online.labels" . | nindent 4 }}
data:
  username: {{ .Values.collabora.username | b64enc }}
  password: {{ .Values.collabora.password | b64enc }}

{{- end }}
