{{- if .Values.dynamicConfig.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "collabora-online.fullname" . }}-dynconfig
  labels:
    {{- include "collabora-online.labels" . | nindent 4 }}
    type: dynconfig
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.dynamicConfig.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "collabora-online.selectorLabels" . | nindent 4 }}
    type: dynconfig
{{- end }}