{{- if .Values.dynamicConfig.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "collabora-online.fullname" . }}-dynconfig
  labels:
    {{- include "collabora-online.labels" . | nindent 4 }}
    type: dynconfig
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.dynamicConfig.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.dynamicConfig.upload.enabled }}
    - port: {{ .Values.dynamicConfig.upload.service.port }}
      targetPort: upload-http
      protocol: TCP
      name: upload-http
    {{- end }}
  selector:
    {{- include "collabora-online.selectorLabels" . | nindent 4 }}
    type: dynconfig
{{- end }}
