{{- if .Values.dynamicConfig.upload.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collabora-online.fullname" . }}-upload-env
  labels:
    {{- include "collabora-online.labels" . | nindent 4 }}
data:
  KEY_{{ .Values.dynamicConfig.upload.key }}: {{ "/config/config.json" | b64enc }}

{{- end }}
