{
 "title": "Collabora Online / Language Tool",
 "tags": [
  "languagetool",
  "collabora",
  "app"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(languagetool_build_info) without(pod,instance)",
     "legendFormat": "v{{ version }} : {{ revision }}"
    }
   ]
  },
  {
   "title": "Check Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(languagetool_check_latency_seconds_bucket{mode!~\".+\"}[$__rate_interval])) by (le))",
     "legendFormat": "100 %"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(languagetool_check_latency_seconds_bucket{mode!~\".+\"}[$__rate_interval])) by (le))",
     "legendFormat": "99 %"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(languagetool_check_latency_seconds_bucket{mode!~\".+\"}[$__rate_interval])) by (le))",
     "legendFormat": "95 %"
    }
   ]
  },
  {
   "title": "Check Latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(languagetool_check_latency_seconds_bucket{mode!~\".+\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checks per Seconds",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(languagetool_checks_total[$__rate_interval])) without(pod,instance)",
     "legendFormat": "{{mode}}: {{ language }}"
    }
   ]
  }
 ]
}