{{- if and .Values.reverseProxy.enabled .Values.reverseProxy.ingress.enabled -}}
{{- $fullName := include "collabora-online.fullname" . -}}
{{- $svcPort := .Values.reverseProxy.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-reverseproxy
  labels:
    {{- include "collabora-online.reverseproxy.labels" . | nindent 4 }}
  {{- with .Values.reverseProxy.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.reverseProxy.ingress.className }}
  ingressClassName: {{ .Values.reverseProxy.ingress.className }}
  {{- end }}
  {{- if .Values.reverseProxy.ingress.tls }}
  tls:
    {{- range .Values.reverseProxy.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.reverseProxy.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}-reverseproxy
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
