name: Add add-pr-to-project

on:
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          project-url: https://github.com/users/pedropintosilva/projects/1
          github-token: ${{ secrets.projectSecret }}
