name: Add add-pr-to-project
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/pedropintosilva/projects/1
          github-token: ${{ secrets.projectSecret || github.token || secrets.ENVPAT}}
