on: [pull_request]

jobs:
  dry-code-action:
    runs-on: ubuntu-latest
    name: Dry Code Action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Dry Code Action
        uses: Pposong-Hantaihe/dry-code@v1.0.2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          arguments: "./browser/src"
          options: "--min-lines=26"

